### ISSUE TITLE
Image reference for 2.37 in CLusterServiceVersion points to the wrong SHA256

### ISSUE THREAD

**Issue by solipsistadventurer** [artemiscloud/activemq-artemis-operator#1039]
The ClusterServiceVersion manifest contains references to the init and kubernetes images on quay.io. These links are based on their SHA256 digest.
However, the ClusterServiceVersion for Operator version 1.2.5 appears to reference the wrong SHA256 for the corresponding version 2.37.0 application images on quay.io

image: **activemq-artemis-broker-init:artemis.2.37.0**
CSV: [e2a761725d5b](https://github.com/artemiscloud/activemq-artemis-operator/blob/09e6ae8e88e5b1b12087586398a2b8f51314be51/bundle/manifests/activemq-artemis-operator.clusterserviceversion.yaml#L3303)
Quay.io: [b6f61188379d](https://quay.io/repository/artemiscloud/activemq-artemis-broker-init/manifest/sha256:b6f61188379def8c796c738549c099bd40bcd9bb44f5c30682c5edd136347aca)

image: **activemq-artemis-broker-kubernetes:artemis.2.37.0**
CSV: [cd9a01cfe791](https://github.com/artemiscloud/activemq-artemis-operator/blob/09e6ae8e88e5b1b12087586398a2b8f51314be51/bundle/manifests/activemq-artemis-operator.clusterserviceversion.yaml#L3305)
Quay.io: [5e768aefade6](https://quay.io/repository/artemiscloud/activemq-artemis-broker-kubernetes/manifest/sha256:5e768aefade6d18cd65cb1eb5ee233844f9f7e7b52631f93a0982b67d382239d)

**Comment by brusdev** [comment]
@solipsistadventurer the artemis tags are floating tags, it means that they are updated if a new image of the same Apache ActiveMQ Artemis version is built. The ArtemisCloud Operator 1.2.5 was released after [activemq-artemis-broker-kubernetes-image 1.0.31](https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/commits/1.0.31) and before [activemq-artemis-broker-kubernetes-image 1.0.32](https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/commits/1.0.32) that are both based on Apache ActiveMQ Artemis 2.37.0. This is the reason why the SHA256 for the corresponding version 2.37.0 in the ClusterServiceVersion manifest 1.2.5 points to the [activemq-artemis-broker-kubernetes-image 1.0.31](https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/commits/1.0.31) image and the tag artemis.2.37.0 points to the [activemq-artemis-broker-kubernetes-image 1.0.32](https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/commits/1.0.32) image.

**Comment by brusdev** [comment]
@solipsistadventurer of course, the next release will include a ClusterServiceVersion manifest with the updated SHA256.

**Comment by brusdev** [comment]
@solipsistadventurer thanks for sharing your considerations and suggesion.

The related images in the ArtemisCloud Operator Bundle manifest use SHA256 to avoid any misalignment and to work smoothly in a disconnected OpenShift cluster. The images should be synced by using their SHA256 and you could use the oc-mirror plugin to mirror all the required images for a specific operator.

The artemis tags could point to more updated images but the operator should use the images with the SHA256 in the manifest because those are the only ones tested.

The artemis tags should be considered as a latest tag for a specific artemis version, they are not supposed to be used in production.

The users can use the fields `spec.DeploymentPlan.image` and `spec.DeploymentPlan.initImage` to customize the deplyment container images.

I agree with you that tying the Artemis image and Operator releases would avoid the gap between the latest artemis tag and the SHA256 in the manifest but that would increase the number of the operator releases and the required effort. This is way the release of the containers is decoupled from the operator release.

**Comment by solipsistadventurer** [comment]
I understand your position and your desire to limit the number of Operator releases.

As a final remark - and I promise I will stop after this :-) - is that as a user / administrator I find it confusing that the Artemis version can be configured in the Custom Resource, but this is not necessarily in sync with the application image with the same version tag. In a connected environment this is not a problem, since the 'old' image with the referenced SHA256 also exists in the registry. But in an airgapped environment I have no way of knowing which application image I need to sync to the local registry - unless I dig deep into the CSV with lots of custom scripting, which I would like to avoid.
I think that this can easily be solved procedurally: once an application image is released, there should no newer image with the same version tag. In case there is a critical issue that requires an immediate solution, imho this would actually also warrant a new Operator release, despite all required effort.

As a FINAL final remark I would like to thank you for all your great work on this operator :-)

Regards,
Lucas

**Comment by brusdev** [comment]
@solipsistadventurer thanks for your feedback. I see your point of view but when the operator is installed using OLM the only source of truth should be the bundle manifest and SHA256s should help avoiding misalignments due to floating tags in an airgapped environment. You could use the following command lines to loop on the related images of a specific bundle version:

Loop on the related images of Artemis version 2.38.0 of the bundle 1.2.6
```
BUNDLE_VERSION='1.2.6'
ARTEMIS_VERSION='2.38.0'
RELATED_IMAGES=$(curl -sL https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/refs/tags/${BUNDLE_VERSION}/bundle/manifests/activemq-artemis-operator.clusterserviceversion.yaml | sed -n "/- name: RELATED_IMAGE.*${ARTEMIS_VERSION//./}/,/value:/ s/.*value:\\(.*\\)/\\1/p")
for RELATED_IMAGE in ${RELATED_IMAGES}; do echo "<${RELATED_IMAGE}>"; done
```

Loop on all the related images of the bundle 1.2.6
```
BUNDLE_VERSION='1.2.6'
ARTEMIS_VERSION=''
RELATED_IMAGES=$(curl -sL https://raw.githubusercontent.com/artemiscloud/activemq-artemis-operator/refs/tags/${BUNDLE_VERSION}/bundle/manifests/activemq-artemis-operator.clusterserviceversion.yaml | sed -n "/- name: RELATED_IMAGE.*${ARTEMIS_VERSION//./}/,/value:/ s/.*value:\\(.*\\)/\\1/p")
for RELATED_IMAGE in ${RELATED_IMAGES}; do echo "<${RELATED_IMAGE}>"; done
```
