### ISSUE TITLE
Configuring autoscaling of broker pods.

### ISSUE THREAD

**Issue by sachinsaju** [artemiscloud/activemq-artemis-operator#124]
**Is your feature request related to a problem? Please describe.**
We can manually scale up and scale down artemis brokers via ActiveMQArtemis custom resource. But when I add horizontal pod autoscaling to artemis statefulset, initially brokers willl be scaled and after the scaling ,the operator will scale down to the number specified in ActiveMQArtemis CR. So HPA tries to bring up more pod and ActiveMQArtemis CR tries to bring down pods one after another.

**Describe the solution you'd like**
I would like to have Kubernetes handle autoscaling the artemis pods based on resources and Artemis operator manage the message migration when pod goes down. We can either have some fields in ActiveMQArtemis CR to mention HPA details or have a different custom resource for autoscaling.

**Additional context**
I didn't find any detail on HPA autoscaling in the documentation. If I miss something, please let me know.

**Comment by brusdev** [comment]
@sachinsaju could you explain why the horizontal pod autoscaling is required in your use case?

**Comment by gtully** [comment]
I think we should support the scale sub resource. Particularly for the scale to zero use case, where this is a single broker that can be auto scaled between 0 and 1 with the same PV.
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource

**Comment by gtully** [comment]
the HPA use case seems more involved, with metrics etc, and to make it work there would need to be a cluster service that can expose all brokers. As a general rule, partitioning is necessary to have brokers work better at scale with point to point messaging. For multicast, there can be benefits with bridges/federation rather than a plain cluster. this may be non trivial to configure.

To enable the possibility of HPA we need to come up with a selector path, should it contain the ArtemisCR name?

https://book.kubebuilder.io/reference/generating-crd.html?highlight=subre#scale

**Comment by sachinsaju** [comment]
@brusdev There is chance of large number of active queues and messages potentially in my use case. Therefore, If pods can be scaled up or down based on load, it would be helpful . In that way , I can ensure better load balancing to artemis pods(thereby increasing overall performance of apps). HPA is a common feature in most of the k8s tool installations. We can avoid manual scale up or scale down.

**Comment by gtully** [comment]
https://github.com/artemiscloud/activemq-artemis-operator/pull/526 via support for a scale subresource will get the ball rolling on this capability.
