### ISSUE TITLE
QUESTION: Adding broker.xml as a configmap 

### ISSUE THREAD

**Issue by bunnyyy** [artemiscloud/activemq-artemis-operator#160]
Can I add broker.xml as config map.

**Comment by gaohoward** [comment]
Hi I think you can put the broker.xml into a configmap in the way you like, and mount the configmap in the broker use this prop:
https://github.com/artemiscloud/activemq-artemis-operator/blob/42c5a27d23938975ef192500a2382fa6c8169ce0/api/v1beta1/activemqartemis_types.go#L230
You then need to make a custom init image to copy the broker.xml from the mounted configmap to the broker's /etc dir
Here are some examples showing how to use init container:
https://github.com/artemiscloud/artemiscloud-examples/tree/main/operator/init

**Comment by mattlegall** [comment]
Hi @gaohoward 

Is overwriting the default broker.xml completly using a config map going against the documentation at https://artemiscloud.io/docs/tutorials/initcontainer/ which states:
"For configuration that _isn’t_ exposed in the CRD, you can specify a custom Init Container image to manipulate or add to the configuration that has been created by the Operator."

Or do I misinterpret the documentation?

Thanks

**Comment by mattlegall** [comment]
Hi, any thoughts on the question above? I am not aware of what the operator is doing under the hood and I just want to use it correctly.

My 2 cents: since there is a technical way to overwrite broker.xml entirely, I believe the doc should not state the bold part hereafter "**For configuration that isn’t exposed in the CRD,** you can specify a custom Init Container image to manipulate or add to the configuration that has been created by the Operator."

**Comment by brusdev** [comment]
To replace the `broker.xml` file you need to know how the operator works under the hood to deploy a cluster of brokers and to apply address and security CRs.

The `broker.xml` file should be overwritten only if CRDs and brokerProperties are not sufficient to set the required broker settings. What broker settings do you need to set?

**Comment by mattlegall** [comment]
Among other things, we are using broker-plugins, diverts and security-settings and these are not exposed in the CRDs.

The main reason why we would like to overwrite broker.xml is because we have a big legacy of existing broker.xml that were deployed in broker VMs. The rewrite task from broker.xml to CR would be huge to migrate this existing configuration from VMs to K8S.

If we were to use the approach described in https://github.com/artemiscloud/artemiscloud-examples/blob/main/operator/init/jdbc/custom-init/config/post-config.sh, we would have to do so many changes that the script would not be readable. While the simple reuse of existing broker.xml guarantees that we are not making unwanted functional changes (and drastically decrease the amount of testing we have to do).

To understand the broker.xml generated by the operator, we deployed a simple version of it. Then we have incorporated the clustering  (broadcast-groups, discovery-groups and cluster-connections) and scaleDown acceptor from the generated broker.xml into our legacy broker.xml. Clustering and message migration are working smoothly this way.

**Comment by brusdev** [comment]
I see your point, your procedure to overwrite the broker.xml LGTM but it requires a big effort each time you need to upgrade to a newer version. You could already use brokerProperties to define diverts and security-settings and I created a new issue to support broker plugins too, for further detail see #468

**Comment by mattlegall** [comment]
Thanks for your inputs. Two questions:

1) We will not be the only ones having this use case, i.e. many other people will migrate from VM to K8S with a legacy of xml. I came across a broker-security-settings.xml containing <security-settings xmlns="urn:activemq:core"> of more than 1000 lines (and we have many of them). So is there a migration tool from xml to CR by any chance?

2) Or else can we have a file alternative to brokerProperties to allow including legacy files in the CR? For instance for artemis-roles.properties, artemis-users.properties, broker-acceptors.xml, broker-addresses.xml, broker-bridges.xml, broker-connectors.xml, broker-security-settings.xml, cert-roles.properties and cert-users.properties files.

**Comment by brusdev** [comment]
The migration tool is a nice idea to explore but I'm not aware of similar tools. The only availabe solution to avoid the conversion of your current config files is using a custom init image as suggested by @gaohoward, for further details see https://artemiscloud.io/docs/tutorials/initcontainer/

**Comment by mattlegall** [comment]
The legacy broker.xml has been modularized into many xmls like broker-addresses.xml, broker-security-settings.xml, broker-bridges.xml, broker-plugins,etc.,
In the Artemis CRD, can we have support to include these xml templates directly into the broker.xml generated by the operator.
For Example:
  ```
spec:
     security-settings:
       xml-template: <path to broker-security-settings.xml>
     ..
     ..
     bridges:
       xml-template: <path to broker-bridges.xml>
```

**Comment by brusdev** [comment]
ArtemisCloud Operator already offers 2 solutions to define the broker configuration: brokerProperties or custom Init Containers. I think the default Init Container could be improved to import all required broker xml files from a configMap so would just need to create a configMap with the broker xml files and set an env vars to point the default Init Container to the configMap mount point. Would this solution work for you?

**Comment by gaohoward** [comment]
@mattlegall Going forward we are encouraging people to use broker.Properties. However for cases like yours there are many customized config files so I think we need some enhancements to address them. Currently I think you can use init images to just copy your configure files directly to broker's /etc dir (and remove the default ones you don't need). Of course you need to make sure your configuration works with the broker version in the image.
