### ISSUE TITLE
Failover setup

### ISSUE THREAD

**Issue by bbroniewski** [artemiscloud/activemq-artemis-operator#624]
Hi,

Is it possible to setup failover with live and backup instances with shared storage?

Like mentioend here:
https://activemq.apache.org/components/artemis/documentation/1.0.0/ha.html

I see "clustered" configuration and "size".

...but if I understand it correctly, it just spread load over instances, but messages sent to instance "A" will not be picked up by instance 
 "B" if instance "A" will go down.

**Comment by brusdev** [comment]
@bbroniewski the live/backup deployment is not supported by this operator because it doesn't match the Kubernetes philosophy. The operator relays on Kubernetes to restart a faulty broker instance and provides the [message migration feature](https://artemiscloud.io/docs/tutorials/scaleup_and_scaledown/) if you need to scale down your broker cluster.

**Comment by bbroniewski** [comment]
@brusdev Thank you for the explanation! I was not aware it also migrates messages in case of failure.

Do I need to use ReadWriteMany storage type for those workloads?
If one broker pod will keeps crushing, then I believe extra pod to migrate messages will not be bale to attach the volume if it will be ReadWriteOnce.
