### ISSUE TITLE
documentation: update operator documentation

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-operator#846]
In [the documentation](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/docs/help/bundle.md#create-a-catalog-source-eg-catalog-sourceyaml) the catalog source's `yaml` file references an outdated operator that can't be downloaded from the quay repository:

```
spec:
  sourceType: grpc
  image: quay.io/hgao/operator-catalog:v0.0.1
```

Proposed fix: The private repo `quay.io/hgao` should be removed by the public doc

**Comment by brusdev** [comment]
Could make sense to use a floating tag like `latest` to avoid outdated docs in future.

**Comment by brusdev** [comment]
After taking a deeper look to the current [bundle.md](https://github.com/artemiscloud/activemq-artemis-operator/blob/1.2.0/docs/help/bundle.md), I think it require a deeper refactoring:

1. The steps to [build the bundle image](https://github.com/artemiscloud/activemq-artemis-operator/blob/1.2.0/docs/help/bundle.md#building-the-bundle-image) should be removed because now the CI workflow push the official bundle images to quay.io/artemiscloud/activemq-artemis-operator-bundle
2. The `v` prefix should be removed from the tag versions
3. The private repo `quay.io/hgao` should be removed by the public doc
4. The catalog image tag should not match the operator version because a catalog image usually hosts multiple operators

**Comment by Msarawan** [comment]
Closed as completed.
